name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  dockerize:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "Building docker image"
  deploy:
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
      - run: echo "deploying to environment"
  build-db-image:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building data docker image"
  trigger-PR-e2es:
    needs: [build-db-image, deploy]
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/pull') }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.E2E_TRIGGER }}
          repository: benkn/e2e-testing
          event-type: trigger-tests
          client-payload: '{"partner": "${{ github.sha }}", "test_env": "dev"}'
  trigger-main-e2es:
    needs: [build-db-image, deploy]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.E2E_TRIGGER }}
          repository: benkn/e2e-testing
          event-type: trigger-tests
          client-payload: '{"partner": "${{ github.sha }}", "test_env": "dev"}'
  trigger-staging-e2es:
    needs: [build-db-image, deploy]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/staging' }}
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.E2E_TRIGGER }}
          repository: benkn/e2e-testing
          event-type: trigger-tests
          client-payload: '{"partner": "${{ github.sha }}", "test_env": "staging"}'
